global:
  resolve_timeout: 5m

route:
  receiver: "email-alert"

receivers:
  - name: "email-alert"
    email_configs:
      - to: "your-email@gmail.com"
        from: "your-email@gmail.com"
        smarthost: "smtp.gmail.com:587"
        auth_username: "your-email@gmail.com"
        auth_password: "YOUR_APP_PASSWORD"
